const fs = require('fs');

let content = fs.readFileSync('src/InteractivePlot.tsx', 'utf8');

const replacements = {
  'saddle_point': "      tourSteps = [         { text: \"This is a classic **Saddle Point**. Notice how the shape curves like a Pringles chip.\" },         { text: \"Exactly in the center, the ground is flat. Here, the gradient is 0. This is a **Critical Point**.\", highlights: [0, 1], changes: { layout: { scene: { annotations: [{ x: 0, y: 0, z: 0, text: 'Critical Point ∇f=0', showarrow: true, arrowhead: 2, ax: 40, ay: -50, bgcolor: 'rgba(255,255,255,0.8)' }] } } } },         { text: \"Look along the x-axis: it curves *upwards* like a bowl.\", changes: { layout: { scene: { annotations: [{ x: 1.5, y: 0, z: 2.25, text: 'Curves Up', showarrow: true, arrowhead: 2, arrowcolor: 'green', ax: 30, ay: -30, bgcolor: 'rgba(255,255,255,0.8)' }] } } } },         { text: \"Now look along the y-axis: it curves *downwards* into a valley. Because it goes up and down, it's a saddle.\", changes: { layout: { scene: { annotations: [{ x: 0, y: 1.5, z: -2.25, text: 'Curves Down', showarrow: true, arrowhead: 2, arrowcolor: 'red', ax: -30, ay: -30, bgcolor: 'rgba(255,255,255,0.8)' }] } } } }      ];",
  'lagrange_multiplier': "      tourSteps = [         { text: \"With **Lagrange Multipliers**, we maximize a function subject to a constraint.\" },         { text: \"The red loop is our constraint curve. You can think of it as a walking trail.\", changes: { layout: { annotations: [{ x: 1.8, y: 1.5, text: 'Constraint Path', showarrow: true, arrowhead: 2, ax: 50, ay: -20, bgcolor: 'white' }] } } },         { text: \"The extreme values happen exactly where a blue contour level is **tangent** to the red constraint line.\", changes: { layout: { annotations: [{ x: -0.7, y: 1.7, text: 'Point of Tangency', showarrow: true, arrowhead: 3, arrowcolor: 'green', ax: -50, ay: -50, bgcolor: 'white' }] } } },         { text: \"At these tangent points, their gradients point in the exact same direction.\" }      ];",
  'double_integral': "      tourSteps = [         { text: \"A **Double Integral** perfectly sums up infinite microscopic volume blocks.\" },         { text: \"This 3D surface is our function. Notice how the height changes.\", changes: { layout: { scene: { annotations: [{ x: 1.5, y: 1.5, z: 2.5, text: 'Roof z=f(x,y)', showarrow: true, arrowhead: 2, ax: 50, ay: -30, bgcolor: 'rgba(255,255,255,0.8)' }] } } } },         { text: \"We evaluate it as iterated 1D integrals using Fubini's Theorem.\", changes: { layout: { scene: { annotations: [{ x: 0, y: 0, z: 0, text: 'Base Area dA', showarrow: true, arrowhead: 2, ax: -50, ay: 20, bgcolor: 'rgba(255,255,255,0.8)' }] } } } },         { text: \"The differential area dA in the xy-plane becomes our block's base.\" }      ];",
  'center_of_mass': "      tourSteps = [         { text: \"Using Double Integrals, we can find the exact **Center of Mass**.\" },         { text: \"This blue triangle represents a thin plate with uniform density. We find its total mass.\", changes: { layout: { annotations: [{ x: 1, y: 0.5, text: 'Total Mass M', showarrow: true, arrowhead: 1, ax: 50, ay: -30, bgcolor: 'white' }] } } },         { text: \"Then, we compute the 'Moments' to find the balance coordinates.\" },         { text: \"The red crosshair marks this exact geometric balance point. It balances perfectly!\", changes: { layout: { annotations: [{ x: 0.66, y: 0.66, text: 'Centroid', showarrow: true, arrowhead: 3, arrowcolor: 'red', ax: 50, ay: -50, bgcolor: 'white' }] } } }      ];",
  'contour_paraboloid': "      tourSteps = [         { text: \"This is a **Contour Plot**—a 2D map of our 3D paraboloid mountain from above.\" },         { text: \"Each circle represents a specific altitude (a constant z value).\", changes: { layout: { annotations: [{ x: 5, y: 0, text: 'Level Curve', showarrow: true, arrowhead: 2, ax: 60, ay: 30, bgcolor: 'white' }] } } },         { text: \"Notice the distance between rings. Closer lines mean a steeper slope in 3D!\", changes: { layout: { annotations: [{ x: 9, y: 0, text: 'Steeper (close)', showarrow: true, arrowhead: 2, arrowcolor: 'red', ax: 50, ay: -30, bgcolor: 'white' }, { x: 2, y: 0, text: 'Flatter', showarrow: true, arrowhead: 2, arrowcolor: 'green', ax: 50, ay: 30, bgcolor: 'white' }] } } }      ];",
  'gradient_field': "      tourSteps = [        { text: \"This plot shows the contour lines of the saddle function.\" },        { text: \"The gradient is drawn as arrows. Notice every arrow points in the direction of steepest ascent.\", changes: { layout: { annotations: [{ x: 1, y: 0, text: 'Steepest Uphill Direction', showarrow: true, arrowhead: 2, arrowcolor: 'red', ax: 50, ay: -30, bgcolor: 'white' }] } } },        { text: \"At each point, the gradient vector is completely perpendicular to the contour line!\", changes: { layout: { annotations: [{ x: 1, y: 1, text: 'Orthogonal', showarrow: true, arrowhead: 2, arrowcolor: 'green', ax: 50, ay: -50, bgcolor: 'white' }] } } },        { text: \"Walking exactly along the gradient direction would take you to higher values fastest.\" }      ];"
};

for (const [caseName, newCode] of Object.entries(replacements)) {
  const caseHeader = "case '" + caseName + "':";
  let startIdx = content.indexOf(caseHeader);
  if (startIdx !== -1) {
    const stepsStartStr = "tourSteps = [";
    const stepsStart = content.indexOf(stepsStartStr, startIdx);
    const endSteps = content.indexOf("];\n", stepsStart);
    if(stepsStart !== -1 && endSteps !== -1) {
       content = content.substring(0, stepsStart) + newCode.trim() + content.substring(endSteps + 2);
    }
  }
}
fs.writeFileSync('src/InteractivePlot.tsx', content, 'utf8');
console.log('done');
